version: '3.7'

services:
  web:
    build: 
      context: ./MyBank_backend/source
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    command: > 
        bash -c "gunicorn MyBank.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    expose:
      - 8000
    env_file:
      - ./MyBank_backend/source/.env.dev
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=backend_twa1
      - POSTGRES_PASSWORD=100101102
      - POSTGRES_DB=test_work_area2

  redis:
    image: 'redis:alpine'
    # ports:
    #   - '6379:6379'
    volumes:
      - redis_data:/var/lib/redis
      - redis.conf:/usr/local/etc/redis/refis.conf

  nginx:
      build: ./nginx
      restart: unless-stopped
      ports:
        - "80:80"
      depends_on:
        - web

volumes:
  postgres_data:
  redis_data:
  redis.conf: