# Generated by Django 4.0.6 on 2022-07-05 20:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30, unique=True, verbose_name='Номер телефона')),
                ('number_account', models.CharField(max_length=30, unique=True, verbose_name='Номер счёта')),
                ('balance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Баланс')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(unique=True, verbose_name='id транзакции')),
                ('status', models.CharField(choices=[('cancelled', 'cancelled'), ('in_process', 'in_process'), ('success', 'success')], max_length=99, verbose_name='Статус транзакции')),
                ('transfer_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('transaction_start_date', models.DateTimeField(auto_now_add=True)),
                ('Transaction_exit_date', models.DateTimeField(null=True)),
                ('transfer_from_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='user.bank_account')),
                ('transfer_to_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='user.bank_account')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=300, verbose_name='Город')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bank_account',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='user.profile'),
        ),
    ]
