# Generated by Django 4.0.6 on 2022-07-06 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
