# Generated by Django 4.0.6 on 2022-07-06 01:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_delete_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(unique=True, verbose_name='id транзакции')),
                ('status', models.CharField(choices=[('cancelled', 'cancelled'), ('in_process', 'in_process'), ('success', 'success')], max_length=99, verbose_name='Статус транзакции')),
                ('transfer_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('transaction_start_date', models.DateTimeField(auto_now_add=True)),
                ('Transaction_exit_date', models.DateTimeField(null=True)),
                ('transfer_from_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='user.bank_account')),
                ('transfer_to_bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='user.bank_account')),
            ],
        ),
    ]
