FROM python:3.10

WORKDIR /usr/src/my_bank

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install netcat -y

RUN pip install --upgrade pip

COPY ./req.txt /usr/src/my_bank

RUN pip install -r req.txt

COPY . .
RUN ["chmod", "+x", "/usr/src/my_bank/entrypoint.dev.sh"]
ENTRYPOINT [ "/usr/src/my_bank/entrypoint.dev.sh" ]
